future-architect/tech-blog

- source/_posts/20181031-aichan2.md
* 引用の間違いを修正
* コードハイライトが効くように修正
> fix code highlight

- source/_posts/20180301-datascience.md
- themes/corporate/layout/_partial/sidebar.ejs
- themes/corporate/layout/_partial/social-button.ejs
- themes/corporate/layout/_widget/advent-calendar.ejs
* fix category typo
* remove google+ icon
* remove oss icon from page
* add advent calender 2018 link
> maintenance page

- source/_posts/20200521-go-tips-4-godoc.md
タイトルがGo Tips連載3になっていたので, Go Tips連載4に修正しました
> chore: タイトルをGo Tips連載4に修正

- source/_posts/20200525-go-tips-7-golangci.md
golangci-lintがgolngci-lintになっている箇所があったので修正
> chore: fix typo

- source/_posts/20200601-春祭り1-gotest.md
See official documentation
- https://golang.org/pkg/cmd/go/internal/test/
> Use -short instead of --short

- source/_posts/20191120-gocon.md
- source/_posts/20200630-go-swagger-tips.md
- source/_posts/20200701-go-openapi3-generator.md
- source/_posts/20200709-go-review-comments.md
> Add Gopher License

- README.md
- source/_posts/20200601-春祭り1-gotest.md
> update item to introduce testing in Go

- themes/corporate/layout/_partial/sidebar-top.ejs
- themes/corporate/layout/_partial/sidebar.ejs
* End tag h2 seen, but there were open elements.
> End tag h2 seen, but there were open elements.

- themes/corporate/layout/_partial/head.ejs
- themes/corporate/layout/_partial/social-button.ejs
* fix html validator error
* Twitterでaタグのtitleをurl encode
> Fix HTML Validator Error

- themes/corporate/layout/_partial/head.ejs
- themes/corporate/layout/_partial/sidebar-top.ejs
> #639 不要なHTML生成を排除

- scripts/featured_post.js
> #638 注目の記事を相対リンク化

- scripts/count_post.js
- themes/corporate/layout/author.ejs
- themes/corporate/layout/category.ejs
* #633
* カテゴリ、タグはなぜか設定できなかったので、著者のみ
> #633 著者の件数表示を追加

- scripts/count_post.js
- themes/corporate/layout/author.ejs
- themes/corporate/layout/category.ejs
- themes/corporate/layout/tag.ejs
> #633 タグ、カテゴリ検索時の件数も表示

- themes/corporate/layout/_partial/head.ejs
- themes/corporate/layout/_partial/social-button.ejs
* 生成HTMLに余計な空行が入っていたので、レイアウトを修正
* #652 ODPのdescriptionが不正だったので修正
> #652 ODPのdescriptionが不正だったので修正

- scripts/count_post.js
- themes/corporate/layout/_partial/head.ejs
> #660 metaタグのkeywords,authorを改善

- source/_posts/20210430a_Go_Conference_2021_Springに登壇しました.md
- themes/corporate/source/metronic/assets/corporate/css/style.css
> タグ周りの見た目の不具合を修正

- themes/corporate/layout/_partial/post/category.ejs
- themes/corporate/source/metronic/assets/corporate/css/style.css
* 各記事ごとの Categories: Programming などの表示の下にbrタグで調整していた
* CSS制御できるように修正
> <br>でレイアウト制御していたのでCSSに寄せる

- themes/corporate/layout/_partial/archive-post.ejs
* #680
* loading="lazy" もついでに付与
* 本来はwidth, heightもセットで付与したいが、そもそも現状ついていないので
> #680 トップページのサムネ一覧のalt属性を追加

- package-lock.json
- package.json
- scripts/image_size.js
- themes/corporate/layout/_partial/archive-post.ejs
* #668
* img-sizeというパッケージを利用すればかなりすんなり
* 懸念
* script直下はやや決め打ち（_config.ymlから取得したほうが良いかもしれない）
> #668 記事一覧のサムネイルのimgタグにwidth,heightを追加

- source/_posts/20210427a_Goのフラットパッケージについて登壇しました.md
- source/_posts/20210430a_Go_Conference_2021_Springに登壇しました.md
- themes/corporate/layout/_partial/social.ejs
> #688 フッターのsocialリンクにaltタグを追加

- themes/corporate/layout/_partial/archive-post.ejs
- themes/corporate/layout/_partial/article.ejs
- themes/corporate/layout/_partial/post/tag.ejs
- themes/corporate/source/metronic/assets/style.css
> #690 記事ヘッダのタグをli要素に変更

- scripts/social_button.js
> .nojekyll を追加

- themes/corporate/layout/_widget/other-blog.ejs
> #694 ポッドキャストのリンクを追加

- themes/corporate/source/metronic/assets/style.css
> #693 h1,h2,h3タグをマウスオーバーするとリンクが表示されるように修正

- themes/corporate/layout/_partial/archive.ejs
> #702 注目の記事をタグより上位に移動

- themes/corporate/layout/_partial/footer.ejs
- themes/corporate/layout/_partial/social.ejs
> #697 無効化していたフッターのリンクを削除

- themes/corporate/layout/_partial/archive.ejs
- themes/corporate/layout/_partial/article.ejs
- themes/corporate/layout/_partial/sidebar-top.ejs
- themes/corporate/layout/_partial/sidebar.ejs
- themes/corporate/source/metronic/assets/style.css
* サイドバーを `<aside>` タグでラップ
* サイドバーの見出しを`<h2>` に変更
> #704 sidebarに<aside>タグを設定

- package-lock.json
- package.json
- scripts/featured_post.js
- themes/corporate/layout/_partial/featured-post.ejs
> #711 ランダムのシードを設定することでURLごとに注目の記事を固定化

- cache_hatebu.json
- cache_pocket.json
- themes/corporate/layout/_partial/head.ejs
> #731 ODP出力のため記事中に画像がない場合は、page.postsのthumbnailから取得するように修正

- scripts/social_button.js
#727
api limitになった場合にはキャッシュから取得する。
> #727 facebook api error handling

- cache_hatebu.json
- cache_pocket.json
- scripts/featured_post.js
- scripts/related-posts.js
- themes/corporate/layout/_partial/archive.ejs
- themes/corporate/layout/_partial/article.ejs
- themes/corporate/layout/_partial/featured-post.ejs
- themes/corporate/source/metronic/assets/style.css
#631
まずはタグ、著者を重み付け無しでカウントする手法で実装。
> #631 タグと著者で関連記事を作成

- scripts/featured_post.js
> #748 機種依存文字を文字実体参照に変更

- themes/corporate/layout/_partial/head.ejs
> #747 画像が存在しないページの場合はodp画像を利用する

- cache_hatebu.json
- scripts/social_button.js
> fix light bugs

- cache_hatebu.json
- scripts/sns_count.js
- source/_posts/20200323-aws-sam.md
- themes/corporate/source/css/theme-styles.styl
> #742 SNS件数が0の場合はテキスト表示

- themes/corporate/layout/_partial/archive.ejs
- themes/corporate/layout/_partial/article.ejs
- themes/corporate/source/metronic/assets/style.css
> #767 自動生成コンテンツと区別するためasideタグを付与

- scripts/related-posts.js
- themes/corporate/layout/_partial/article.ejs
> #793 関連する記事の表示件数を修正

- scripts/featured_post.js
> #796 注目の記事にその記事が入らないようにフィルター

- package-lock.json
- package.json
#798 
https://github.com/dailyrandomphoto/hexo-easy-tags-plugin
を導入。インストールするだけのデフォルト設定で稼働した。
> #798 タグ並び順の大文字・小文字の無視

- themes/corporate/layout/_partial/social-button.ejs
> #789 SNSボタンの領域が狭い

- scripts/related_posts.js
> #817 関連する記事のtitleにledeを付与

- themes/corporate/layout/_partial/sidebar-top.ejs
- themes/corporate/source/css/theme-styles.styl
> #786 ToCの表示

- themes/corporate/source/metronic/assets/style.css
> #823 パンくずリストCSS調整

- themes/corporate/source/metronic/assets/style.css
> ハッシュタグと記事数のフォントサイズなどを微調整

- scripts/related_posts.js
- scripts/sns_count.js
#835 
関連する記事に、SNS件数が付与されたことを確認
> #835 関連記事にSNSカウントを追加

- themes/corporate/source/metronic/assets/style.css
> #834 ハッシュタグの#のフォントサイズ調整

- themes/corporate/source/css/theme-styles.styl
> #837 ソーシャルボタンのflex対応

- themes/corporate/layout/archive.ejs
> 年月単位のページのパンくずリストも正しくなるように修正

- themes/corporate/source/css/theme-styles.styl
- themes/corporate/source/metronic/assets/style.css
> #855 サイドバーのフォントカラーを黒に統一

- themes/corporate/layout/_widget/other-blog.ejs
> #854 Qiitaリンクを追加

- themes/corporate/source/metronic/assets/style.css
> #852 モバイルでタグ一覧を非表示に

- themes/corporate/layout/_partial/sidebar.ejs
- themes/corporate/source/metronic/assets/style.css
> #851 モバイル時にアドベントカレンダーリンクを非表示に

- cache_hatebu.json
- cache_pocket.json
- cache_twitter.json
- themes/corporate/layout/archive.ejs
- themes/corporate/source/metronic/assets/style.css
> #870 パンくずリストの表示修正

- themes/corporate/layout/_partial/head.ejs
> #862 og:imageの最大数の指定

- themes/corporate/layout/_partial/head.ejs
> #877 canonical link

- scripts/author_generator.js
- scripts/sns_count.js
- themes/corporate/layout/author.ejs
- themes/corporate/layout/authors.ejs
- themes/corporate/source/css/theme-styles.styl
> #714 著者一覧ページを作成

- scripts/count_post.js
- themes/corporate/layout/archive.ejs
> #883 投稿件数を表示

- scripts/tags.js
- themes/corporate/layout/tag.ejs
- themes/corporate/layout/tags.ejs
> #716 タグ一覧ページ

- scripts/categories.js
- themes/corporate/layout/categories.ejs
- themes/corporate/source/css/theme-styles.styl
今の所、サイドバー以上の情報を付与できていないため、パンくずリストの更新は行わない
> #715 カテゴリ一覧ページを作成

- themes/corporate/layout/_partial/sidebar.ejs
> #896 ToCに目次という文言を追加

- themes/corporate/layout/_partial/sidebar.ejs
> #905 不要なページに目次が表示されるのを防止

- scripts/author_generator.js
> #909 共著しか記事がない著者を一覧に出力

- scripts/tags.js
- themes/corporate/layout/tags.ejs
- themes/corporate/source/css/theme-styles.styl
> #881 人気のタグ表示を追加

- themes/corporate/layout/_partial/archive-all.ejs
- themes/corporate/source/css/theme-styles.styl
> #914 選択している年をハイライトマーカー

- scripts/author_generator.js
- themes/corporate/layout/authors.ejs
> #864 年次の著者ランキングを表示

- themes/corporate/layout/_partial/post/date.ejs
- themes/corporate/source/css/theme-styles.styl
> #849 日付をリンク化

- themes/corporate/layout/author.ejs
表示時のサイズで表示できることは確認。
ブラウザのサイズ変更すると、JSで再表示が必要
> #921 チャートのレスポンシブ対応

- scripts/author_generator.js
- scripts/lib/sns.js
- themes/corporate/layout/author.ejs
- themes/corporate/source/css/theme-styles.styl
> #920 著者ページにSNSシェアの明細を表示

- scripts/lib/sns.js
> #930 fix bugs

- scripts/sns_count.js
- themes/corporate/_config.yml
- themes/corporate/layout/_partial/archive-post.ejs
- themes/corporate/source/css/theme-styles.styl
#946
Lede文はリンクではなく、 Read moreをクリックする必要
マウスオーバーで本文をグレーに
> Read moreを削除し lede文をリンクに変更

- themes/corporate/source/css/theme-styles.styl
> #942 引用の背景をグレーに変更

- cache_facebook.json
- cache_hatebu.json
- cache_pocket.json
- cache_twitter.json
- scripts/sns_count.js
> #955 キャッシュ取得時にシェア数0の場合にテキスト文言にするように修正

- themes/corporate/source/css/theme-styles.styl
- themes/corporate/source/metronic/assets/style.css
#963
focus の設定を追加
タブ移動でどこにいるかわかるようにした
> #963 focus時にもカラー設定

- themes/corporate/source/css/theme-styles.styl
- themes/corporate/source/metronic/assets/style.css
> #934 カテゴリの挙動を変更

- scripts/count_post.js
- scripts/table_filter.js
- themes/future/layout/author.ejs
- themes/future/layout/category.ejs
- themes/future/source/css/theme-styles.styl
> #929 カテゴリページにサマリ情報を表示

- scripts/count_post.js
- themes/future/layout/tag.ejs
> #928 タグページにサマリ情報を付与

- scripts/author_generator.js
- themes/future/layout/authors.ejs
- themes/future/source/metronic/assets/style.css
> #960 投稿者の推移を表示

- scripts/count_post.js
- themes/future/layout/archive.ejs
> #973 投稿一覧にサマリ情報を表示

- package-lock.json
- scripts/list_tags.js
- scripts/popular_posts.js
- themes/future/layout/_widget/tag.ejs
- themes/future/layout/tags.ejs
- themes/future/source/css/theme-styles.styl
> #927 トップページのタグを5件以上のみ表示

- themes/future/layout/_partial/archive-post.ejs
- themes/future/layout/_partial/post/title.ejs
- themes/future/source/css/theme-styles.styl
- themes/future/source/metronic/assets/style.css
> #976 トップページのタイトルとlede文のリンクを同一化

- themes/future/layout/_partial/footer.ejs
#983
フッターにメディアポリシーを追加。
採用情報やその他問い合わせについても追記。
> #983 メディアポリシーを追加

- themes/future/source/metronic/assets/style.css
#1004 Chrome Developper Toolsで不要なCSSを削除
> #1004 CSS削減

- themes/future/layout/_partial/google-analytics.ejs
google-analytics.jsを読み取りをscriptタグ化
> #1003 script化

- themes/future/_config.yml
- themes/future/layout/_widget/tag.ejs
- themes/future/source/metronic/assets/style.css
> #1015 タグ表示の復活

- themes/future/source/css/theme-styles.styl
> #1017 シェア数が多い場合に発生するCSS崩れを修正

- source/_posts/20210323_Cloud_Spannerのローカル開発環境をdocker-composeでサクッと立ち上げる.md
https://github.com/tarosaiba/docker-compose-spanner
> Fix github url

- README.md
> #630 検知方法を記載

- themes/future/layout/_partial/sidebar.ejs
> formのhttps化

- scripts/archive_post_chart.js
- themes/future/layout/archive.ejs
- themes/future/layout/author.ejs
> #1196 月別投稿数チャートを追加

- scripts/news.js
- themes/future/layout/index.ejs
- themes/future/source/css/theme-styles.styl
> #1271 Qiita投稿をNEWSで通知

- scripts/news.js
- scripts/techcast_latest.js
- themes/future/source/css/theme-styles.styl
https://github.com/future-architect/tech-blog/issues/1199
> #1199 1week以内に公開されたテックキャストのエピソードにNEWラベルを付与

- scripts/popular_posts.js
- scripts/related_posts.js
- scripts/techcast_latest.js
- themes/future/source/css/theme-styles.styl
> #1219 関連記事、人気の記事にNEWラベルを表示

- source/_posts/20210611a_サーバーアプリ開発環境(Python／FastAPI).md
L93~L95のtaskipyの追加と
最後のdockerコンテナ起動する部分にリクエスト送りました。 最後の　. は不要ではないかと思いました。
また、poetryで作成したアプリ名がexample_serverになっていますが、デフォルトだとsample_serverでプロジェクト作成するとアプリ名もsample_serverになるのかなと思いました。(おそらく、２つsample_serverがあるためわかりやすいように区別しているのだと思うのですが。)
> 手を動かしていて気になったところです

- scripts/news.js
https://github.com/future-architect/tech-blog/issues/1304
> fx #1394 NEWSに表示される勉強会の日付を開催日に変更

- package-lock.json
- package.json
- themes/future/layout/authors.ejs
- themes/future/source/css/theme-styles.styl
> fix #1303 著者一覧を2年分表示

- source/_posts/20220204a_Step_Functionsの動的並列処理をローカルで実行する.md
いつも興味深い記事をありがとうございます。
読んでいてtypoに気付き、プルリクエストを送りました
> Fix typo: pikcle

- source/_posts/20240129a_Go_1.22リリース連載始まります_&_ループの変化とTinyGo_0.31.md
記事の公開ありがとうございます。
読んでいる際、恐らく誤字かなという箇所を見つけたのでPRを出しておきます。
> Fix a typo
